"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const auth_1 = require("../config/middlewares/auth");
const admin_controller_1 = require("../modules/admin/admin.controller");
const router = (0, express_1.Router)();
router.use(auth_1.adminAuth);
router.get("/bans", admin_controller_1.getBannedIps);
router.post("/unban", admin_controller_1.unbanIp);
exports.default = router;
